export async function fanExceptionConfigAssetDesc(data) {}
export async function fanExceptionConfiFaultgAsset(data) {}
export async function configLabelList(data) {}
export async function getYCPointList(data) {
  return {
    statusCode: '1000',
    result: 'OK',
    message: '请求成功',
    data: {
      points: [
        {
          labelName: '全站有功发电总加',
          labelValue: 'SUM_P',
        },
        {
          labelName: '35kV耀增线PT同期电压Ux',
          labelValue: 'PT_ux',
        },
        {
          labelName: '35kV耀增线331开关A相电流',
          labelValue: 'Ia',
        },
        {
          labelName: '35kV耀增线331开关B相电流',
          labelValue: '331_Ib',
        },
        {
          labelName: '35kV耀增线331开关C相电流',
          labelValue: '331_Ic',
        },
        {
          labelName: '35kV耀增线331开关有功功率',
          labelValue: 'P',
        },
        {
          labelName: '35kV耀增线331开关无功功率',
          labelValue: 'Q',
        },
        {
          labelName: '35kV耀增线331开关功率因数',
          labelValue: '331_COS',
        },
        {
          labelName: '35kV A母线A相电压',
          labelValue: '35A_V_a',
        },
        {
          labelName: '35kV A母线B相电压',
          labelValue: '35A_V_b',
        },
        {
          labelName: '35kV A母线C相电压',
          labelValue: '35A_V_c',
        },
        {
          labelName: '35kV A母线AB线电压',
          labelValue: 'Uab',
        },
        {
          labelName: '35kV A母线BC线电压',
          labelValue: 'Ubc',
        },
        {
          labelName: '35kV A母线CA线电压',
          labelValue: 'Uca',
        },
        {
          labelName: '35kV A母线3Uo电压',
          labelValue: '35A_V_u0',
        },
        {
          labelName: '35kV A母线频率',
          labelValue: 'Fr',
        },
        {
          labelName: '35kV集电Ⅰ线311开关A相电流',
          labelValue: '311_Ia',
        },
        {
          labelName: '35kV集电Ⅰ线311开关B相电流',
          labelValue: '311_Ib',
        },
        {
          labelName: '35kV集电Ⅰ线311开关C相电流',
          labelValue: '311_Ic',
        },
        {
          labelName: '35kV集电Ⅰ线311开关有功功率',
          labelValue: '311_P',
        },
        {
          labelName: '35kV集电Ⅰ线311开关无功功率',
          labelValue: '311_Q',
        },
        {
          labelName: '35kV集电Ⅰ线311开关功率因素',
          labelValue: '311_COS',
        },
        {
          labelName: '35kV 1#SVG312开关A相电流',
          labelValue: '312_Ia',
        },
        {
          labelName: '35kV 1#SVG312开关B相电流',
          labelValue: '312_Ib',
        },
        {
          labelName: '35kV 1#SVG312开关C相电流',
          labelValue: '312_Ic',
        },
        {
          labelName: '35kV 1#SVG312开关无功功率',
          labelValue: '312_Q',
        },
        {
          labelName: '35kV 1#接地变313开关A相电流',
          labelValue: '313_Ia',
        },
        {
          labelName: '35kV 1#接地变313开关B相电流',
          labelValue: '313_Ib',
        },
        {
          labelName: '35kV 1#接地变313开关C相电流',
          labelValue: '313_Ic',
        },
        {
          labelName: '35kV 1#接地变313开关有功功率',
          labelValue: '313_P',
        },
        {
          labelName: '35kV 1#接地变313开关无功功率',
          labelValue: '313_Q',
        },
        {
          labelName: '1路交流进线交流Uab',
          labelValue: 'ZLP_1_Uab',
        },
        {
          labelName: '1路交流进线交流Ubc',
          labelValue: 'ZLP_1_Ubc',
        },
        {
          labelName: '1路交流进线交流Uca',
          labelValue: 'ZLP_1_Uca',
        },
        {
          labelName: '2路交流进线交流Uab',
          labelValue: 'ZLP_2_Uab',
        },
        {
          labelName: '2路交流进线交流Ubc',
          labelValue: 'ZLP_2_Ubc',
        },
        {
          labelName: '2路交流进线交流Uca',
          labelValue: 'ZLP_2_Uca',
        },
        {
          labelName: '控母电压',
          labelValue: 'ZLP_km_V',
        },
        {
          labelName: '合母电压',
          labelValue: 'ZLP_hm_V',
        },
        {
          labelName: '负载电流',
          labelValue: 'ZLP_fz_A',
        },
        {
          labelName: '电池组电压',
          labelValue: 'ZLP_dc_V',
        },
        {
          labelName: '电池组电流',
          labelValue: 'ZLP_dc_A',
        },
        {
          labelName: '正对地电压',
          labelValue: 'ZLP_zdd_V',
        },
        {
          labelName: '负对地电压',
          labelValue: 'ZLP_fdd_V',
        },
        {
          labelName: '交流屏交流1路Uab线电压',
          labelValue: 'JLP_1_Uab',
        },
        {
          labelName: '交流屏交流1路Ubc线电压',
          labelValue: 'JLP_1_Ubc',
        },
        {
          labelName: '交流屏交流1路Uca线电压',
          labelValue: 'JLP_1_Uca',
        },
        {
          labelName: '交流屏交流1路A相电流',
          labelValue: 'JLP_1_Ia',
        },
        {
          labelName: '交流屏交流1路B相电流',
          labelValue: 'JLP_1_Ib',
        },
        {
          labelName: '交流屏交流1路C相电流',
          labelValue: 'JLP_1_Ic',
        },
        {
          labelName: '交流屏交流2路Uab线电压',
          labelValue: 'JLP_2_Uab',
        },
        {
          labelName: '交流屏交流2路Ubc线电压',
          labelValue: 'JLP_2_Ubc',
        },
        {
          labelName: '交流屏交流2路Uca线电压',
          labelValue: 'JLP_2_Uca',
        },
        {
          labelName: '交流屏交流2路A相电流',
          labelValue: 'JLP_2_Ia',
        },
        {
          labelName: '交流屏交流2路B相电流',
          labelValue: 'JLP_2_Ib',
        },
        {
          labelName: '交流屏交流2路C相电流',
          labelValue: 'JLP_2_Ic',
        },
        {
          labelName: 'UPS1输出电压',
          labelValue: 'UPS1_out_V',
        },
        {
          labelName: 'UPS1输出电流',
          labelValue: 'UPS1_out_A',
        },
        {
          labelName: 'UPS2输出电压',
          labelValue: 'UPS2_out_V',
        },
        {
          labelName: 'UPS2输出电流',
          labelValue: 'UPS2_out_A',
        },
        {
          labelName: '接地电流',
          labelValue: 'DZ_jd_A',
        },
        {
          labelName: '电阻温度',
          labelValue: 'DZ_temp',
        },
        {
          labelName: '环境温度',
          labelValue: 'temp',
        },
        {
          labelName: '环境湿度',
          labelValue: 'DZ_hj_hum',
        },
      ],
    },
  };
}
export async function centerAlertAssetAlert(data) {}
export async function onQueryTagInfo(data) {
  return {
    statusCode: '1000',
    result: 'OK',
    message: '请求成功',
    data: [
      {
        label: 'direct_radiation_instantaneous',
        labelName: '直接辐射瞬时值',
      },
      {
        label: 'dayil_total_direct_radiation',
        labelName: '直接辐射日累计值',
      },
      {
        label: 'total_direct_radiation_time_interval',
        labelName: '直接辐射时间间隔累计值',
      },
      {
        label: 'humidity',
        labelName: '环境湿度',
      },
      {
        label: 'dayil_total_sunshine',
        labelName: '日照日累计值',
      },
      {
        label: 'total_sunshine_interval',
        labelName: '日照时间隔累计值',
      },
      {
        label: 'air_pressure',
        labelName: '气压',
      },
      {
        label: 'scattered_radiation_instantaneous',
        labelName: '散射辐射瞬时值',
      },
      {
        label: 'dayil_total_scattered_radiation',
        labelName: '散射辐射日累计值',
      },
      {
        label: 'total_scattered_radiation_time_interval',
        labelName: '散射辐射时间间隔累计值',
      },
      {
        label: 'temp',
        labelName: '环境温度',
      },
      {
        label: 'Temp_1',
        labelName: '电池板温度',
      },
      {
        label: 'Temp_2',
        labelName: '露点温度',
      },
      {
        label: 'Radiation',
        labelName: '总辐射1瞬时值',
      },
      {
        label: 'Daily_Radiation',
        labelName: '总辐射1日累计值',
      },
      {
        label: 'total_radiation_time_interval_one',
        labelName: '总辐射1时间间隔瞬时值',
      },
      {
        label: 'wind_direction_instantaneous',
        labelName: '风向瞬时值',
      },
      {
        label: 'wind_speed_instantaneous_environment',
        labelName: '风速瞬时值',
      },
      {
        label: 'wind_speed_10m_avg',
        labelName: '10分钟风速',
      },
      {
        label: 'wind_speed_2m_avg',
        labelName: '2分钟风速',
      },
      {
        label: 'date_time',
        labelName: '主要信息时间',
      },
    ],
  };
}
export async function taskCaseList(data) {}
export async function statusList(data) {}
export async function getDeviceInfoByStationDeptNums(data) {
  return {
    statusCode: '1000',
    result: 'OK',
    message: '请求成功',
    data: {
      '01001055': [
        {
          id: 1942495,
          assetnum: '01001055',
          assetname: '右玉耀源风电场     01001055',
          longitude: null,
          latitude: null,
          windModel: null,
          deptNum: '01001055',
          location: 'G001',
          type: 'G',
          agreement: null,
          alterInfo: null,
          thirdClass: 'deptModel',
          model: 'deptModel',
          parentNum: null,
          sortOrder: null,
          data: '{}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942728,
          assetnum: 'E0251000827',
          assetname: '35kV耀增线331断路器',
          longitude: null,
          latitude: null,
          windModel: '3.0',
          deptNum: '0100105501',
          location: null,
          type: 'E',
          agreement: '1002',
          alterInfo: null,
          thirdClass: 'E0251',
          model: 'SHUOZHOU_DLQ',
          parentNum: null,
          sortOrder: null,
          data: '{"eq10":"0100105501","status_desc":"在用","status_type":"select","treeList":[],"diaoDuBianHao1":"331","midclass":"E025","description":"35kV耀增线331断路器","udbelong_desc":"右玉县耀源风电场","smaclass":"E0251","eq10_desc":"一期","manufacturer":"特变电工自控设备有限公司","bxdqr":"","bigclass":"E02","assetnum":"E0251000827","dept_id":4932,"status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942729,
          assetnum: 'E0251000828',
          assetname: '35kV集电I线311断路器',
          longitude: null,
          latitude: null,
          windModel: '3.0',
          deptNum: '0100105501',
          location: null,
          type: 'E',
          agreement: '1002',
          alterInfo: null,
          thirdClass: 'E0251',
          model: 'SHUOZHOU_DLQ',
          parentNum: null,
          sortOrder: null,
          data: '{"unittype":"-","eq10":"0100105501","status_desc":"在用","status_type":"select","treeList":[],"diaoDuBianHao1":"311","ccbh":"-","midclass":"E025","description":"35kV集电I线311断路器","udbelong_desc":"右玉县耀源风电场","smaclass":"E0251","eq10_desc":"一期","manufacturer":"特变电工自控设备有限公司","bxdqr":"2022-08-31","bigclass":"E02","assetnum":"E0251000828","dept_id":4932,"status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942730,
          assetnum: 'E0251000829',
          assetname: '35kV 1号SVG312断路器',
          longitude: null,
          latitude: null,
          windModel: '3.0',
          deptNum: '0100105501',
          location: null,
          type: 'E',
          agreement: '1002',
          alterInfo: null,
          thirdClass: 'E0251',
          model: 'SHUOZHOU_DLQ',
          parentNum: null,
          sortOrder: null,
          data: '{"eq10":"0100105501","status_desc":"在用","status_type":"select","treeList":[],"diaoDuBianHao1":"312","midclass":"E025","description":"35kV 1号SVG312断路器","udbelong_desc":"右玉县耀源风电场","smaclass":"E0251","eq10_desc":"一期","manufacturer":"特变电工自控设备有限公司","bxdqr":"","bigclass":"E02","assetnum":"E0251000829","dept_id":4932,"status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942731,
          assetnum: 'E0251000830',
          assetname: '35kV 1号接地变313断路器',
          longitude: null,
          latitude: null,
          windModel: '3.0',
          deptNum: '0100105501',
          location: null,
          type: 'E',
          agreement: '1002',
          alterInfo: null,
          thirdClass: 'E0251',
          model: 'SHUOZHOU_DLQ',
          parentNum: null,
          sortOrder: null,
          data: '{"unittype":"-","eq10":"0100105501","status_desc":"在用","status_type":"select","treeList":[],"diaoDuBianHao1":"313","ccbh":"-","midclass":"E025","description":"35kV 1号接地变313断路器","udbelong_desc":"右玉县耀源风电场","smaclass":"E0251","eq10_desc":"一期","manufacturer":"特变电工自控设备有限公司","bxdqr":"2022-08-12","bigclass":"E02","assetnum":"E0251000830","dept_id":4932,"status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1943047,
          assetnum: 'E0311001937',
          assetname: '331副表',
          longitude: null,
          latitude: null,
          windModel: null,
          deptNum: '0100105501',
          location: 'T003CFA11',
          type: 'E',
          agreement: null,
          alterInfo: null,
          thirdClass: 'E0311',
          model: 'FJDB',
          parentNum: null,
          sortOrder: null,
          data: '{"eq10":"0100105501","status_desc":"在运","midclass":"E031","description":"331副表","udbelong_desc":"右玉县耀源风电场","smaclass":"E0311","eq10_desc":"一期","bxdqr":"","bigclass":"E03","assetnum":"E0311001937","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1943048,
          assetnum: 'E0311001582',
          assetname: '331主表',
          longitude: null,
          latitude: null,
          windModel: null,
          deptNum: '0100105501',
          location: 'T003CFA11',
          type: 'E',
          agreement: null,
          alterInfo: null,
          thirdClass: 'E0311',
          model: 'FJDB',
          parentNum: null,
          sortOrder: null,
          data: '{"eq10":"0100105501","status_desc":"在用","midclass":"E031","description":"331主表","udbelong_desc":"右玉县耀源风电场","smaclass":"E0311","eq10_desc":"一期","manufacturer":"威胜集团有限公司","bxdqr":"","bigclass":"E03","assetnum":"E0311001582","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1943049,
          assetnum: 'E0311001584',
          assetname: '311电能表',
          longitude: null,
          latitude: null,
          windModel: null,
          deptNum: '0100105501',
          location: 'T003CFA11',
          type: 'E',
          agreement: null,
          alterInfo: null,
          thirdClass: 'E0311',
          model: 'FJDB',
          parentNum: null,
          sortOrder: null,
          data: '{"eq10":"0100105501","status_desc":"在用","midclass":"E031","description":"311电能表","udbelong_desc":"右玉县耀源风电场","smaclass":"E0311","eq10_desc":"一期","manufacturer":"威胜集团有限公司","bxdqr":"","bigclass":"E03","assetnum":"E0311001584","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1943050,
          assetnum: 'E0311001585',
          assetname: '312电能表',
          longitude: null,
          latitude: null,
          windModel: null,
          deptNum: '0100105501',
          location: 'T003CFA11',
          type: 'E',
          agreement: null,
          alterInfo: null,
          thirdClass: 'E0311',
          model: 'FJDB',
          parentNum: null,
          sortOrder: null,
          data: '{"eq10":"0100105501","status_desc":"在用","midclass":"E031","description":"312电能表","udbelong_desc":"右玉县耀源风电场","smaclass":"E0311","eq10_desc":"一期","manufacturer":"威胜集团有限公司","bxdqr":"","bigclass":"E03","assetnum":"E0311001585","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1943051,
          assetnum: 'E0311001586',
          assetname: '313电能表',
          longitude: null,
          latitude: null,
          windModel: null,
          deptNum: '0100105501',
          location: 'T003CFA11',
          type: 'E',
          agreement: null,
          alterInfo: null,
          thirdClass: 'E0311',
          model: 'FJDB',
          parentNum: null,
          sortOrder: null,
          data: '{"eq10":"0100105501","status_desc":"在用","midclass":"E031","description":"313电能表","udbelong_desc":"右玉县耀源风电场","smaclass":"E0311","eq10_desc":"一期","manufacturer":"威胜集团有限公司","bxdqr":"","bigclass":"E03","assetnum":"E0311001586","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942079,
          assetnum: 'G0010550001',
          assetname: '1号风机',
          longitude: '112.5582908',
          latitude: '39.87375286',
          windModel: '3.0',
          deptNum: '0100105501',
          location: 'G001',
          type: 'G',
          agreement: '1004',
          alterInfo: null,
          thirdClass: 'G0001',
          model: 'JF25',
          parentNum: null,
          sortOrder: null,
          data: '{"fengJiJingDu":"112.558290805555","yePianXingHao":"GW73.2A","chiLunXiangChangJia":"无","fengJiGaoDu":"1400","ccbh":"GOLDWIND-2800-2021020-1","taTongXingShi":"柔塔","description":"1号风机","udbelong_desc":"右玉县耀源风电场","rated_P":"2500","eq10_desc":"一期","bianJiangZhouChengChangJia":"洛阳新能","manufacturer":"金风科技","bingWangShiJian":"2021-12-31","bianLiuXiTong":"海得","yePianChangJia":"中科宇能","bianJiangZhouChengXingHao":"040.75.2650.03K","biaoGanJiZu":"否","jiShuLuXian":"直驱","assetnum":"G0010550001","taTongGaoDu":"140","jiDianXianLuDesc":"集电一线","bianJiangXiTong":"国产","lengQueFangShi":"风冷","yeLunZhiJing":"150","shiYanJiZu_desc":"否","jiChuXingShi":"锚栓","unittype":"GW150/2500","shiYanJiZu":"否","daoSongDianShiJian":"2021-12-31","eq10":"0100105501","status_desc":"在运","jiZuFenLei":"2.5","guZhangBanBenHao":"2.5","bxdqr":"","jiDianXianLu":"I","fengJiWeiDu":"39.8737528611111","chu240ShiJian":"","faDianJiChangJia":"金风","zhuKongBanBen":"2000 GW V200630 T211221","fengSuYi":"贝良","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942080,
          assetnum: 'G0010550002',
          assetname: '2号风机',
          longitude: '112.5552509',
          latitude: '39.87071869',
          windModel: '3.0',
          deptNum: '0100105501',
          location: 'G002',
          type: 'G',
          agreement: '1004',
          alterInfo: null,
          thirdClass: 'G0001',
          model: 'JF25',
          parentNum: null,
          sortOrder: null,
          data: '{"fengJiJingDu":"112.555250888888","yePianXingHao":"GW73.2A","chiLunXiangChangJia":"无","fengJiGaoDu":"1400","ccbh":"GOLDWIND-2800-2021020-2","taTongXingShi":"柔塔","description":"2号风机","udbelong_desc":"右玉县耀源风电场","rated_P":"2500","eq10_desc":"一期","bianJiangZhouChengChangJia":"洛阳新能","manufacturer":"金风科技","bingWangShiJian":"2021-12-31","bianLiuXiTong":"海得","yePianChangJia":"中科宇能","bianJiangZhouChengXingHao":"040.75.2650.03K","biaoGanJiZu":"否","jiShuLuXian":"直驱","assetnum":"G0010550002","taTongGaoDu":"140","jiDianXianLuDesc":"集电一线","bianJiangXiTong":"国产","lengQueFangShi":"风冷","yeLunZhiJing":"150","shiYanJiZu_desc":"否","jiChuXingShi":"锚栓","unittype":"GW150/2500","shiYanJiZu":"否","daoSongDianShiJian":"2021-12-31","eq10":"0100105501","status_desc":"在运","jiZuFenLei":"2.5","guZhangBanBenHao":"2.5","bxdqr":"","jiDianXianLu":"I","fengJiWeiDu":"39.8707186944444","chu240ShiJian":"","faDianJiChangJia":"金风","zhuKongBanBen":"2000 GW V200630 T211221","fengSuYi":"贝良","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942081,
          assetnum: 'G0010550003',
          assetname: '3号风机',
          longitude: '112.5415204',
          latitude: '39.88021886',
          windModel: '3.0',
          deptNum: '0100105501',
          location: 'G003',
          type: 'G',
          agreement: '1004',
          alterInfo: null,
          thirdClass: 'G0001',
          model: 'JF25',
          parentNum: null,
          sortOrder: null,
          data: '{"fengJiJingDu":"112.541520361111","yePianXingHao":"GW73.2A","chiLunXiangChangJia":"无","fengJiGaoDu":"1400","ccbh":"GOLDWIND-2800-2021020-3","taTongXingShi":"柔塔","description":"3号风机","udbelong_desc":"右玉县耀源风电场","rated_P":"2500","eq10_desc":"一期","bianJiangZhouChengChangJia":"洛阳新能","manufacturer":"金风科技","bingWangShiJian":"2021-12-31","bianLiuXiTong":"海得","yePianChangJia":"中科宇能","bianJiangZhouChengXingHao":"040.75.2650.03K","biaoGanJiZu":"否","jiShuLuXian":"直驱","assetnum":"G0010550003","taTongGaoDu":"140","jiDianXianLuDesc":"集电一线","bianJiangXiTong":"国产","lengQueFangShi":"风冷","yeLunZhiJing":"150","shiYanJiZu_desc":"否","jiChuXingShi":"锚栓","unittype":"GW150/2500","shiYanJiZu":"否","daoSongDianShiJian":"2021-12-31","eq10":"0100105501","status_desc":"在运","jiZuFenLei":"2.5","guZhangBanBenHao":"2.5","bxdqr":"","jiDianXianLu":"I","fengJiWeiDu":"39.8802188611111","chu240ShiJian":"","faDianJiChangJia":"金风","zhuKongBanBen":"2000 GW V200630 T211221","fengSuYi":"科瑞文","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942082,
          assetnum: 'G0010550004',
          assetname: '4号风机',
          longitude: '112.5929589',
          latitude: '39.90399158',
          windModel: '3.0',
          deptNum: '0100105501',
          location: 'G004',
          type: 'G',
          agreement: '1004',
          alterInfo: null,
          thirdClass: 'G0001',
          model: 'JF25',
          parentNum: null,
          sortOrder: null,
          data: '{"fengJiJingDu":"112.592958888888","yePianXingHao":"GW73.2A","chiLunXiangChangJia":"无","fengJiGaoDu":"1400","ccbh":"GOLDWIND-2800-2021020-4","taTongXingShi":"柔塔","description":"4号风机","udbelong_desc":"右玉县耀源风电场","rated_P":"2500","eq10_desc":"一期","bianJiangZhouChengChangJia":"罗特艾德","manufacturer":"金风科技","bingWangShiJian":"2021-12-31","bianLiuXiTong":"海得","yePianChangJia":"中科宇能","bianJiangZhouChengXingHao":"BD.M.2650.B0.F2","biaoGanJiZu":"否","jiShuLuXian":"直驱","assetnum":"G0010550004","taTongGaoDu":"140","jiDianXianLuDesc":"集电一线","bianJiangXiTong":"国产","lengQueFangShi":"风冷","yeLunZhiJing":"150","shiYanJiZu_desc":"否","jiChuXingShi":"锚栓","unittype":"GW150/2500","shiYanJiZu":"否","daoSongDianShiJian":"2021-12-31","eq10":"0100105501","status_desc":"在运","jiZuFenLei":"2.5","guZhangBanBenHao":"2.5","bxdqr":"","jiDianXianLu":"I","fengJiWeiDu":"39.9039915833333","chu240ShiJian":"","faDianJiChangJia":"金风","zhuKongBanBen":"2000 GW V200630 T211221","fengSuYi":"贝良","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942083,
          assetnum: 'G0010550005',
          assetname: '5号风机',
          longitude: '112.5849627',
          latitude: '39.91558161',
          windModel: '3.0',
          deptNum: '0100105501',
          location: 'G005',
          type: 'G',
          agreement: '1004',
          alterInfo: null,
          thirdClass: 'G0001',
          model: 'JF25',
          parentNum: null,
          sortOrder: null,
          data: '{"fengJiJingDu":"112.584962722222","yePianXingHao":"GW73.2A","chiLunXiangChangJia":"无","fengJiGaoDu":"1400","ccbh":"GOLDWIND-2800-2021020-5","taTongXingShi":"柔塔","description":"5号风机","udbelong_desc":"右玉县耀源风电场","rated_P":"2500","eq10_desc":"一期","bianJiangZhouChengChangJia":"罗特艾德","manufacturer":"金风科技","bingWangShiJian":"2021-12-31","bianLiuXiTong":"海得","yePianChangJia":"中科宇能","bianJiangZhouChengXingHao":"BD.M.2650.B0.F2","biaoGanJiZu":"否","jiShuLuXian":"直驱","assetnum":"G0010550005","taTongGaoDu":"140","jiDianXianLuDesc":"集电一线","bianJiangXiTong":"国产","lengQueFangShi":"风冷","yeLunZhiJing":"150","shiYanJiZu_desc":"否","jiChuXingShi":"锚栓","unittype":"GW150/2500","shiYanJiZu":"否","daoSongDianShiJian":"2021-12-31","eq10":"0100105501","status_desc":"在运","jiZuFenLei":"2.5","guZhangBanBenHao":"2.5","bxdqr":"","jiDianXianLu":"I","fengJiWeiDu":"39.9155816111111","chu240ShiJian":"","faDianJiChangJia":"金风","zhuKongBanBen":"2000 GW V200630 T211221","fengSuYi":"贝良","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942084,
          assetnum: 'G0010550006',
          assetname: '6号风机',
          longitude: '112.5883046',
          latitude: '39.92770933',
          windModel: '3.0',
          deptNum: '0100105501',
          location: 'G006',
          type: 'G',
          agreement: '1004',
          alterInfo: null,
          thirdClass: 'G0001',
          model: 'JF25',
          parentNum: null,
          sortOrder: null,
          data: '{"fengJiJingDu":"112.588304611111","yePianXingHao":"GW73.2A","chiLunXiangChangJia":"无","fengJiGaoDu":"1400","ccbh":"GOLDWIND-2800-2021020-6","taTongXingShi":"柔塔","description":"6号风机","udbelong_desc":"右玉县耀源风电场","rated_P":"2500","eq10_desc":"一期","bianJiangZhouChengChangJia":"洛阳新能","manufacturer":"金风科技","bingWangShiJian":"2021-12-31","bianLiuXiTong":"海得","yePianChangJia":"中复连众","bianJiangZhouChengXingHao":"040.75.2650.03K","biaoGanJiZu":"否","jiShuLuXian":"直驱","assetnum":"G0010550006","taTongGaoDu":"140","jiDianXianLuDesc":"集电一线","bianJiangXiTong":"国产","lengQueFangShi":"风冷","yeLunZhiJing":"150","shiYanJiZu_desc":"否","jiChuXingShi":"锚栓","unittype":"GW150/2500","shiYanJiZu":"否","daoSongDianShiJian":"2021-12-31","eq10":"0100105501","status_desc":"在运","jiZuFenLei":"2.5","guZhangBanBenHao":"2.5","bxdqr":"","jiDianXianLu":"I","fengJiWeiDu":"39.9277093333333","chu240ShiJian":"","faDianJiChangJia":"金风","zhuKongBanBen":"2000 GW V200630 T211221","fengSuYi":"科瑞文","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942085,
          assetnum: 'G0010550007',
          assetname: '7号风机',
          longitude: '112.581374',
          latitude: '39.92991817',
          windModel: '3.0',
          deptNum: '0100105501',
          location: 'G007',
          type: 'G',
          agreement: '1004',
          alterInfo: null,
          thirdClass: 'G0001',
          model: 'JF25',
          parentNum: null,
          sortOrder: null,
          data: '{"fengJiJingDu":"112.581373972222","yePianXingHao":"GW73.2A","chiLunXiangChangJia":"无","fengJiGaoDu":"1400","ccbh":"GOLDWIND-2800-2021020-7","taTongXingShi":"柔塔","description":"7号风机","udbelong_desc":"右玉县耀源风电场","rated_P":"2500","eq10_desc":"一期","bianJiangZhouChengChangJia":"洛阳新能","manufacturer":"金风科技","bingWangShiJian":"2021-12-31","bianLiuXiTong":"海得","yePianChangJia":"艾朗","bianJiangZhouChengXingHao":"040.75.2650.03K","biaoGanJiZu":"否","jiShuLuXian":"直驱","assetnum":"G0010550007","taTongGaoDu":"140","jiDianXianLuDesc":"集电一线","bianJiangXiTong":"国产","lengQueFangShi":"风冷","yeLunZhiJing":"150","shiYanJiZu_desc":"否","jiChuXingShi":"锚栓","unittype":"GW150/2500","shiYanJiZu":"否","daoSongDianShiJian":"2021-12-31","eq10":"0100105501","status_desc":"在运","jiZuFenLei":"2.5","guZhangBanBenHao":"2.5","bxdqr":"","jiDianXianLu":"I","fengJiWeiDu":"39.9299181666666","chu240ShiJian":"","faDianJiChangJia":"金风","zhuKongBanBen":"2000 GW V200630 T211221","fengSuYi":"贝良","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942086,
          assetnum: 'G0010550008',
          assetname: '8号风机',
          longitude: '112.5951359',
          latitude: '39.93000317',
          windModel: '3.0',
          deptNum: '0100105501',
          location: 'G008',
          type: 'G',
          agreement: '1004',
          alterInfo: null,
          thirdClass: 'G0001',
          model: 'JF25',
          parentNum: null,
          sortOrder: null,
          data: '{"fengJiJingDu":"112.595135944444","yePianXingHao":"GW73.2A","chiLunXiangChangJia":"无","fengJiGaoDu":"1400","ccbh":"GOLDWIND-2800-2021020-8","taTongXingShi":"柔塔","description":"8号风机","udbelong_desc":"右玉县耀源风电场","rated_P":"2500","eq10_desc":"一期","bianJiangZhouChengChangJia":"罗特艾德","manufacturer":"金风科技","bingWangShiJian":"2021-12-31","bianLiuXiTong":"海得","yePianChangJia":"艾朗","bianJiangZhouChengXingHao":"BD.M.2650.B0.F2","biaoGanJiZu":"否","jiShuLuXian":"直驱","assetnum":"G0010550008","taTongGaoDu":"140","jiDianXianLuDesc":"集电一线","bianJiangXiTong":"国产","lengQueFangShi":"风冷","yeLunZhiJing":"150","shiYanJiZu_desc":"否","jiChuXingShi":"锚栓","unittype":"GW150/2500","shiYanJiZu":"否","daoSongDianShiJian":"2021-12-31","eq10":"0100105501","status_desc":"在运","jiZuFenLei":"2.5","guZhangBanBenHao":"2.5","bxdqr":"","jiDianXianLu":"I","fengJiWeiDu":"39.9300031666666","chu240ShiJian":"","faDianJiChangJia":"金风","zhuKongBanBen":"2000 GW V200630 T211221","fengSuYi":"科瑞文","status":"2"}',
          stationDeptNum: '01001055',
        },
        {
          id: 1943139,
          assetnum: 'Link01001055',
          assetname: '通讯链路',
          longitude: null,
          latitude: null,
          windModel: null,
          deptNum: '01001055',
          location: null,
          type: 'D',
          agreement: null,
          alterInfo: null,
          thirdClass: 'Link',
          model: 'Link',
          parentNum: null,
          sortOrder: null,
          data: '{}',
          stationDeptNum: '01001055',
        },
        {
          id: 1942501,
          assetnum: 'E0991100999',
          assetname: '升压站',
          longitude: '112.34096688',
          latitude: '39.52207687',
          windModel: null,
          deptNum: '0100105501',
          location: null,
          type: 'P',
          agreement: null,
          alterInfo: null,
          thirdClass: 'SYZ01',
          model: 'SHUOZHOU_ZZ',
          parentNum: null,
          sortOrder: null,
          data: '{"eq10":"0100105501","status_desc":"在运","midclass":"SYZ0","description":"升压站","udbelong_desc":"右玉县耀源风电场","smaclass":"SYZ01","eq10_desc":"一期","bxdqr":"","bigclass":"SYZ","assetnum":"E0991100999","status":"2"}',
          stationDeptNum: '01001055',
        },
      ],
    },
  };
}
export async function windPowerPredictionNameList(data) {}
export async function fanExceptionConfigAsset(data) {}
export async function deviceStatusInfo(data) {}
export async function getStrategyPhotovoltaic(data) {}
export async function workflowProcessStatus(data) {}
export async function updateStrategy(data) {}
export async function resetDefault(data) {}
